# Overcommit configuration for sequel-duckdb
# See https://github.com/sds/overcommit for documentation

PreCommit:
  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop']
    flags: ['--autocorrect']
    include:
      - '**/*.rb'
      - '**/*.rake'
      - '**/Rakefile'
      - '**/Gemfile'
      - '**/*.gemspec'

  RakeTarget:
    enabled: true
    targets: ['test']
    description: 'Run test suite'

  BundleAudit:
    enabled: false

  TrailingWhitespace:
    enabled: true
    exclude:
      - '**/*.md'

  MergeConflicts:
    enabled: true

  YamlSyntax:
    enabled: true

  JsonSyntax:
    enabled: true

  HardTabs:
    enabled: true
    exclude:
      - '**/Makefile*'
      - '**/*.mk'

CommitMsg:
  TextWidth:
    enabled: true
    max_subject_width: 60
    max_body_width: 72

PostCheckout:
  BundleCheck:
    enabled: true

PostMerge:
  BundleCheck:
    enabled: true

PostRewrite:
  BundleCheck:
    enabled: true
