inherit_gem: { rubocop-rails-omakase: rubocop.yml }
plugins: [rubocop-minitest, rubocop-rake, rubocop-sequel]
Lint:
  Enabled: true
AllCops:
  TargetRubyVersion: 3.3
  Exclude: [vendor/**/*, bin/**/*, tmp/**/*, claude_stuff/**/*]
